"""Initial schema: users, cameras, camera_zones, events, recordings, system_settings, audit_logs

Revision ID: 0001
Revises:
Create Date: 2026-08-05

Hand-written (not autogenerated) to match app/db models exactly, since the
sandbox this was authored in has no live Postgres to run reliable
autogenerate against. Every column/type/constraint below was cross-checked
against the corresponding SQLAlchemy model in app/modules/*/model.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users (app/modules/auth/model.py) ──
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False, server_default="viewer"),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)

    # ── cameras (app/modules/cameras/model.py) ──
    op.create_table(
        "cameras",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("location_label", sa.String(length=200), server_default=""),
        sa.Column("rtsp_url_encrypted", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="offline"),
        sa.Column("record_enabled", sa.Boolean(), server_default=sa.true()),
        sa.Column("retention_days", sa.Integer(), server_default="14"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ── camera_zones ──
    op.create_table(
        "camera_zones",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "camera_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cameras.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("polygon_json", sa.Text(), server_default="[]"),
        sa.Column("zone_type", sa.String(length=50), server_default="detection"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ── events (app/modules/events/model.py) ──
    op.create_table(
        "events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "camera_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cameras.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("subtype", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Float(), server_default="0.0"),
        sa.Column("importance", sa.String(length=20), server_default="medium"),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("clip_path", sa.String(length=500), nullable=True),
        sa.Column("clip_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("alerted", sa.Boolean(), server_default=sa.false()),
        sa.Column("review_status", sa.String(length=50), server_default="pending"),
        sa.Column("metadata_json", sa.Text(), server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_events_event_type", "events", ["event_type"])
    op.create_index("ix_events_started_at", "events", ["started_at"])

    # ── recordings (app/modules/recordings/model.py) ──
    op.create_table(
        "recordings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "camera_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cameras.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), server_default="0"),
        sa.Column("duration_seconds", sa.Float(), server_default="0.0"),
        sa.Column("resolution", sa.String(length=50), server_default=""),
        sa.Column("status", sa.String(length=50), server_default="recording"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_recordings_camera_id", "recordings", ["camera_id"])
    op.create_index("ix_recordings_start_time", "recordings", ["start_time"])
    op.create_index("ix_recordings_status", "recordings", ["status"])

    # ── system_settings (app/modules/settings/model.py) ──
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=200), primary_key=True),
        sa.Column("value_json", sa.Text(), server_default="{}"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ── audit_logs ──
    op.create_table(
        "audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "actor_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=True),
        sa.Column("details_json", sa.Text(), server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("system_settings")
    op.drop_index("ix_recordings_status", table_name="recordings")
    op.drop_index("ix_recordings_start_time", table_name="recordings")
    op.drop_index("ix_recordings_camera_id", table_name="recordings")
    op.drop_table("recordings")
    op.drop_index("ix_events_started_at", table_name="events")
    op.drop_index("ix_events_event_type", table_name="events")
    op.drop_table("events")
    op.drop_table("camera_zones")
    op.drop_table("cameras")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
