"""ml_models table + cameras detection columns (YOLO detection backend port)

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-28

Hand-written (not autogenerated), matching the style of 0001_initial_schema.py
and cross-checked against app/modules/ml_models/model.py and
app/modules/cameras/model.py.

ml_models must be created before the cameras.model_id FK column, since that
column references ml_models.id.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── ml_models (app/modules/ml_models/model.py) ──
    op.create_table(
        "ml_models",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False, server_default="pt"),
        sa.Column("source", sa.String(length=20), nullable=False, server_default="custom"),
        sa.Column("class_names_json", sa.Text(), server_default="[]"),
        sa.Column("is_default", sa.Boolean(), server_default=sa.false()),
        sa.Column("size_bytes", sa.Integer(), server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ── cameras: detection columns (app/modules/cameras/model.py) ──
    op.add_column("cameras", sa.Column("detect_enabled", sa.Boolean(), server_default=sa.false()))
    op.add_column(
        "cameras",
        sa.Column("detect_backend", sa.String(length=20), server_default="motion"),
    )
    op.add_column(
        "cameras",
        sa.Column(
            "model_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("ml_models.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.add_column(
        "cameras", sa.Column("confidence_threshold", sa.Float(), server_default="0.5")
    )
    op.add_column(
        "cameras", sa.Column("detect_class_ids_json", sa.Text(), server_default="[]")
    )
    op.add_column("cameras", sa.Column("alert_enabled", sa.Boolean(), server_default=sa.true()))
    op.add_column(
        "cameras", sa.Column("alert_cooldown_seconds", sa.Integer(), server_default="30")
    )
    op.add_column(
        "cameras", sa.Column("mqtt_publish_enabled", sa.Boolean(), server_default=sa.false())
    )
    op.add_column(
        "cameras", sa.Column("cot_publish_enabled", sa.Boolean(), server_default=sa.false())
    )
    # Static surveyed camera position for CoT plotting only \u2014 not target
    # geolocation (no range/bearing math was ported).
    op.add_column("cameras", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("cameras", sa.Column("longitude", sa.Float(), nullable=True))


def downgrade() -> None:
    op.drop_column("cameras", "longitude")
    op.drop_column("cameras", "latitude")
    op.drop_column("cameras", "cot_publish_enabled")
    op.drop_column("cameras", "mqtt_publish_enabled")
    op.drop_column("cameras", "alert_cooldown_seconds")
    op.drop_column("cameras", "alert_enabled")
    op.drop_column("cameras", "detect_class_ids_json")
    op.drop_column("cameras", "confidence_threshold")
    op.drop_column("cameras", "model_id")
    op.drop_column("cameras", "detect_backend")
    op.drop_column("cameras", "detect_enabled")
    op.drop_table("ml_models")
