"""Devices (MQTT sensor ingestion) + make events.camera_id nullable, add events.device_id

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-15

Hand-written (not autogenerated) to match app/db models exactly, following
the same convention as 0001_initial_schema.py. Adds the devices table
(app/modules/devices/model.py) for non-camera sensors ingested over MQTT
(ESPHome / Zigbee2MQTT), and widens events so the same table can carry
either a camera_id or a device_id.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── devices (app/modules/devices/model.py) ──
    op.create_table(
        "devices",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("location_label", sa.String(length=200), server_default=""),
        sa.Column("protocol", sa.String(length=50), nullable=False),
        sa.Column("mqtt_topic", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="offline"),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true()),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.Text(), server_default="{}"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_devices_device_type", "devices", ["device_type"])
    op.create_index("ix_devices_mqtt_topic", "devices", ["mqtt_topic"])

    # ── events: camera_id becomes optional, device_id added ──
    op.alter_column(
        "events", "camera_id", existing_type=postgresql.UUID(as_uuid=True), nullable=True
    )
    op.add_column(
        "events",
        sa.Column(
            "device_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("devices.id", ondelete="CASCADE"),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("events", "device_id")
    op.alter_column(
        "events", "camera_id", existing_type=postgresql.UUID(as_uuid=True), nullable=False
    )

    op.drop_index("ix_devices_mqtt_topic", table_name="devices")
    op.drop_index("ix_devices_device_type", table_name="devices")
    op.drop_table("devices")
